import esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

function writeMergedStyles() {
  const root = process.cwd();
  const comshitCss = path.join(root, "styles-comshit.css");
  const excelCss = path.join(root, "excel-modded", "styles.css");
  const outCss = path.join(root, "styles.css");
  const a = fs.readFileSync(comshitCss, "utf8");
  const b = fs.readFileSync(excelCss, "utf8");
  fs.writeFileSync(outCss, `${a}\n\n/* --- excel-modded (bundled) --- */\n\n${b}`);
}

const context = await esbuild.context({
  plugins: [
    {
      name: "merge-styles",
      setup(build) {
        build.onEnd((result) => {
          if (result.errors.length === 0) writeMergedStyles();
        });
      },
    },
  ],
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
